server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  messages:
    basename: i18n/message
    encoding: UTF-8
    default-locale: en
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: 2bAj/kzDz2mWaPmoCfJ6MyZmZRBQAhs2pAMnxZpQKIA=